### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by wuyuancai** [pxb1988/dex2jar#518] opened 2021-12-04 07:50 UTC
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.googlecode.d2j.reader.DexFileReader.getString(DexFileReader.java:970)
        at com.googlecode.d2j.reader.DexFileReader.getField(DexFileReader.java:923)
        at com.googlecode.d2j.reader.DexFileReader.acceptField(DexFileReader.java:989)
        at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:850)
        at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:662)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:117)
        at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:110)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:88)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

**Comment by ThexXTURBOXx** [comment] 2021-12-04 22:17
Well... The error message pretty much tells you what is wrong with your setup :)
Try starting dex2jar with the `-Xmx` parameter to specify the amount of RAM that Java may utilize (for more help, the Java documentation may be your friend)

**Comment by itsmekingtiger** [comment] 2022-08-28 06:30
**Windows**

`d2j_invoke.bat`

```diff
...
-java -Xms512m -Xmx2048m -cp "%CP%" %*
+java -Xms512m -Xmx8g -cp "%CP%" %*
```



**Linux/Mac**

`d2j-dex2jar.sh`

```diff
...
-java -Xms512m -Xmx2048m -classpath "${_classpath}" "com.googlecode.dex2jar.tools.Dex2jarCmd" "$@"
+java -Xms512m -Xmx8g -classpath "${_classpath}" "com.googlecode.dex2jar.tools.Dex2jarCmd" "$@"
```

**Comment by ThexXTURBOXx** [comment] 2023-09-02 19:18
Duplicate of #178

**Closed as not planned by ThexXTURBOXx** 2023-09-02 19:18 UTC
