### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [pxb1988/dex2jar#178] opened 2018-05-08 09:43 UTC
Tried latest night build, got the following exception

Uncaught translation error: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
Uncaught translation error: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
2 errors; aborting

**Comment by ysh329** [comment] 2019-12-05 04:28
same issue

**Comment by ysh329** [comment] 2019-12-05 04:29
```shell
# ./dex-tools-2.1-SNAPSHOT/d2j-dex2jar.sh -f ./aweme_aweGW_v8.8.0_55fb587.apk
dex2jar ./aweme_aweGW_v8.8.0_55fb587.apk -> ./aweme_aweGW_v8.8.0_55fb587-dex2jar.jar
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:101)
	at com.googlecode.d2j.reader.DexFileReader.getString(DexFileReader.java:964)
	at com.googlecode.d2j.reader.DexFileReader.getType(DexFileReader.java:975)
	at com.googlecode.d2j.reader.DexFileReader.getField(DexFileReader.java:917)
	at com.googlecode.d2j.reader.DexFileReader.acceptInsn(DexFileReader.java:1595)
	at com.googlecode.d2j.reader.DexFileReader.acceptCode(DexFileReader.java:1407)
	at com.googlecode.d2j.reader.DexFileReader.acceptMethod(DexFileReader.java:1058)
	at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:856)
	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:659)
	at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:116)
	at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:109)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:88)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:275)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)
```

**Comment by radityagumay** [comment] 2020-12-21 02:35
hi is there any updates on this?

**Comment by itsmekingtiger** [comment] 2022-08-28 06:31
**Windows**

`d2j_invoke.bat`

```diff
...
-java -Xms512m -Xmx2048m -cp "%CP%" %*
+java -Xms512m -Xmx8g -cp "%CP%" %*
```



**Linux/Mac**

`d2j-dex2jar.sh`

```diff
...
-java -Xms512m -Xmx2048m -classpath "${_classpath}" "com.googlecode.dex2jar.tools.Dex2jarCmd" "$@"
+java -Xms512m -Xmx8g -classpath "${_classpath}" "com.googlecode.dex2jar.tools.Dex2jarCmd" "$@"
```

**Comment by ThexXTURBOXx** [comment] 2023-09-02 19:18
Duplicate of #178

**Closed as not planned by ThexXTURBOXx** 2023-09-02 19:18 UTC
