### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [pxb1988/dex2jar#602] opened 2023-09-02 19:07 UTC
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:101)
	at com.googlecode.d2j.reader.DexFileReader.getString(DexFileReader.java:970)
	at com.googlecode.d2j.reader.DexFileReader.getMethod(DexFileReader.java:959)
	at com.googlecode.d2j.reader.DexFileReader.acceptInsn(DexFileReader.java:1647)
	at com.googlecode.d2j.reader.DexFileReader.acceptCode(DexFileReader.java:1413)
	at com.googlecode.d2j.reader.DexFileReader.acceptMethod(DexFileReader.java:1064)
	at com.googlecode.d2j.reader.DexFileReader.acceptClass(DexFileReader.java:862)
	at com.googlecode.d2j.reader.DexFileReader.accept(DexFileReader.java:662)
	at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:117)
	at com.googlecode.d2j.reader.MultiDexFileReader.accept(MultiDexFileReader.java:110)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:86)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:285)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

**Comment by ThexXTURBOXx** [comment] 2023-09-02 19:17
You need to increase the amount of RAM allocated to Java.
Duplicate of #178 (solution given in [this comment](https://github.com/pxb1988/dex2jar/issues/178#issuecomment-1229391012) in particular)

**Closed as not planned by ThexXTURBOXx** 2023-09-02 19:17 UTC
